Created wrapper function around docker-compose to allow alternate compose file, with docker-compose.yml as default

diff --git a/bin/sail b/bin/sail
--- a/bin/sail
+++ b/bin/sail
@@ -43,6 +43,13 @@ function sail_is_not_running {
     exit 1
 }
 
+# Wrapper around docker-compose -f <alternate compose file> to avoid conflicts with projects already using docker-compose
+function docker_compose {
+    local file="${SAIL_DOCKER_COMPOSE_FILE:-docker-compose.yml}"
+    [ -f "$file" ] || { echo -e "Missing file ${WHITE}${file}${NC}"; exit 2; }
+    docker-compose -f "$file" "$@"
+}
+
 if [ -z "$SAIL_SKIP_CHECKS" ]; then
     # Ensure that Docker is running...
     if ! docker info > /dev/null 2>&1; then
@@ -52,11 +59,11 @@ if [ -z "$SAIL_SKIP_CHECKS" ]; then
     fi
 
     # Determine if Sail is currently up...
-    PSRESULT="$(docker-compose ps -q)"
-    if docker-compose ps | grep $APP_SERVICE | grep 'Exit'; then
+    PSRESULT="$(docker_compose ps -q)"
+    if docker_compose ps | grep $APP_SERVICE | grep 'Exit'; then
         echo -e "${WHITE}Shutting down old Sail processes...${NC}" >&2
 
-        docker-compose down > /dev/null 2>&1
+        docker_compose down > /dev/null 2>&1
 
         EXEC="no"
     elif [ -n "$PSRESULT" ]; then
@@ -74,7 +81,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 php "$@"
@@ -87,7 +94,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 ./vendor/bin/"$@"
@@ -100,7 +107,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 composer "$@"
@@ -113,7 +120,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 php artisan "$@"
@@ -126,7 +133,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 -e XDEBUG_SESSION=1 \
                 "$APP_SERVICE" \
@@ -140,7 +147,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 php artisan test "$@"
@@ -153,7 +160,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 -e "APP_URL=http://${APP_SERVICE}" \
                 -e "DUSK_DRIVER_URL=http://selenium:4444/wd/hub" \
@@ -168,7 +175,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 -e "APP_URL=http://${APP_SERVICE}" \
                 -e "DUSK_DRIVER_URL=http://selenium:4444/wd/hub" \
@@ -183,7 +190,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 php artisan tinker
@@ -196,7 +203,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 node "$@"
@@ -209,7 +216,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 npm "$@"
@@ -222,7 +229,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 npx "$@"
@@ -235,7 +242,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 yarn "$@"
@@ -248,7 +255,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 mysql \
                 bash -c 'MYSQL_PWD=${MYSQL_PASSWORD} mysql -u ${MYSQL_USER} ${MYSQL_DATABASE}'
         else
@@ -260,7 +267,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 mariadb \
                 bash -c 'MYSQL_PWD=${MYSQL_PASSWORD} mysql -u ${MYSQL_USER} ${MYSQL_DATABASE}'
         else
@@ -272,7 +279,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                  pgsql \
                  bash -c 'PGPASSWORD=${PGPASSWORD} psql -U ${POSTGRES_USER} ${POSTGRES_DB}'
         else
@@ -284,7 +291,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 -u sail \
                 "$APP_SERVICE" \
                 bash "$@"
@@ -297,7 +304,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 "$APP_SERVICE" \
                 bash "$@"
         else
@@ -309,7 +316,7 @@ if [ $# -gt 0 ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker-compose exec \
+            docker_compose exec \
                 redis \
                 redis-cli
         else
@@ -333,8 +340,8 @@ if [ $# -gt 0 ]; then
 
     # Pass unknown commands to the "docker-compose" binary...
     else
-        docker-compose "$@"
+        docker_compose "$@"
     fi
 else
-    docker-compose ps
+    docker_compose ps
 fi
